### ISSUE TITLE
ACL group mapping inconsistency

### ISSUE THREAD

**Issue by srd424** [brauner/mount-idmapped#9] opened 2022-07-03 10:19 UTC
If this is a bug at all I guess it's in the kernel now, but I hope it's OK to raise it here for @brauner's attention?

I've `mount-idmapped` some layers and a working directory for overlayfs:
```
~/mount-idmapped --map-mount=b:0:1000000:65536 /vol/contpool/images/nuc-armtest@20220701-2053 /vol/contpool/lowermap
rm -r ctrover/over/*
~/mount-idmapped --map-mount=b:0:1000000:65536 /vol/contpool/ctrover/ /vol/contpool/overmap/
```
The ACL on /var/log/journal in the lower is as expected:
```
# getfacl -n images/nuc-armtest@20220701-2053/var/log/journal/ | egrep '^group:.+:'
group:4:r-x
# getfacl -n lowermap/var/log/journal | egrep '^group:.+:'
group:1000004:r-x
```
Now if I overlay mount and enter a userns, the ACL doesn't seem to be mapped correctly:
```
# mount -t overlay overlay \
 -olowerdir=/vol/contpool/lowermap,upperdir=/vol/contpool/overmap/over,workdir=/vol/contpool/overmap/work \
 ctrtest
# ~/mount-idmapped --map-caller=b:0:1000000:65536 /vol/contpool/ctrtest /vol/contpool/mnt
# getfacl -n mnt/var/log/journal | egrep '^group:.+:'
group:4294967295:r-x
```
The inode owner is mapped fine:
```
# ls -ldn lowermap/var/log/journal
drwxr-sr-x+ 1 1000000 1000101 0 Jan  1  1970 lowermap/var/log/journal
# ls -ldn mnt/var/log/journal
drwxr-sr-x+ 1 0 101 0 Jan  1  1970 mnt/var/log/journal
```
It makes systemd whinge if the container is actually started with LXC:
```
Jul 03 10:15:17 nuc-armtest systemd-tmpfiles[25]: Setting access ACL "u::rwx,g::r-x,g:adm:r-x,g:4294967295:r-x,m::r-x,o::r-x" on /var/log/journal failed: Invalid argument
Jul 03 10:15:17 nuc-armtest systemd-tmpfiles[25]: Setting access ACL "u::rwx,g::r-x,g:adm:r-x,g:4294967295:r-x,m::r-x,o::r-x" on /var/log/journal/09d026f380e840ddbd7868fcf40d55b7 failed: Invalid argument
Jul 03 10:15:17 nuc-armtest systemd-tmpfiles[25]: Setting access ACL "u::rw-,g::r-x,g:adm:r--,g:4294967295:r-x,m::r--,o::---" on /var/log/journal/09d026f380e840ddbd7868fcf40d55b7/system.journal failed: Invalid argument
```
This is using 5.19rc4:
```
# uname -r
5.19.0-051900rc4-generic
```

**Comment by brauner** [comment] 2022-07-03 11:57
I'll take a look this week.

**Comment by brauner** [comment] 2022-07-03 15:14
Can you show me the output of dmesg after your ran the reproducer, please? This is not a bug btw. I'm just trying to confirm what exactly your're doing and that my explanation is correct.

**Comment by srd424** [comment] 2022-07-03 15:58
Ah, good catch, after the overlay mount:
```
[187397.677895] overlayfs: failed to create directory /vol/contpool/overmap/work/work (errno: 75); mounting read-only
```
I presume that's causing problems, but I think I've run out of brain today to understand why it's happening..

**Comment by srd424** [comment] 2022-07-03 16:29
Interestingly, I don't see that message if I let LXC setup the overlay mount with:
```
lxc.rootfs.path = overlayfs:/vol/contpool/lowermap:/vol/contpool/overmap/over
```
But the ACL is still wrong, and systemd moans in the container as above. The mount as it shows up in the container is:
```
/vol/contpool/lowermap on / type overlay (rw,relatime,lowerdir=/vol/contpool/lowermap,upperdir=/vol/contpool/overmap/over,workdir=/vol/contpool/overmap/work)
```

Possibly I'm trying to do something that still isn't quite supported - I will admit to not having the deepest understanding of how this should all work. The underlying filesystem on /vol/contpool is btrfs, if that's relevant.

**Comment by srd424** [comment] 2022-07-03 16:41
LXC of course runs the mount in a new user namespace, so:
```
 lxc-usernsexec -m b:0:1000000:65536
# in spawned shell:
mount -t overlay overlay  -olowerdir=/vol/contpool/lowermap,upperdir=/vol/contpool/overmap/over,workdir=/vol/contpool/overmap/work  ctrtest
```
Is more correct and replicates what it's doing. I do also see in the dmesg output:
```
Jul 03 17:38:47 nuc kernel: overlayfs: upper fs does not support xattr, falling back to xino=off.
```
Which looks like it could well be relevant..

**Comment by srd424** [comment] 2022-07-03 16:57
Adding `-o userxattr` turns the error message into
```
Jul 03 17:55:12 nuc kernel: overlayfs: fs on '/vol/contpool/lowermap' does not support file handles, falling back to xino=off.
```
But the behaviour of `getfacl /var/log/journal` is unchanged.

**Comment by brauner** [comment] 2022-07-05 08:31
Still working on this.

**Comment by srd424** [comment] 2022-07-15 19:57
Just seen the updates here - thanks! Don't know why github doesn't send notifications in this case ...

**Comment by brauner** [comment] 2022-08-02 07:13
This is now fixed upstream.

**Closed as completed by brauner** 2022-08-02 07:13 UTC
